/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oop.Customer;

public class App {


    public static void main(String[] args) {
        Customer c1 = new Customer ("Puji Prakoso","Bengkulu");
        Order order1 = new Order ("Baju",50000,2);
        c1.order(order1);
        
        
    }
}
